- name: Single Node Kubernetes
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
  - name: Update package cache
    apt:
      update_cache: true
      #cache_valid_time: 3600
  
  - name: Install required dependencies
    package:
      name:
      - wget
      - apt-transport-https
      - ca-certificates 
      - gnupg
      state: present
  
  - name: Download the public signing key
    get_url:
      url: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key"
      dest: "/tmp/kubernetes-gpg-key"
      mode: '0644'

  - name: Create /etc/apt/keyrings directory
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: "0755"

  - name: Import Kubernetes GPG key
    command: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-gpg-key"
    #ignore_errors: true

  - name: Add the Kubernetes repository
    shell: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list"
  
  - name:
    apt:
      update_cache: true
  
  roles:
  - single-node-kube