---
- name: Create k8s.conf file with required kernel modules
  ansible.builtin.template:
    src: ../templates/kernel_modules.j2
    dest: /etc/modules-load.d/k8s.conf

- name: Load kernel modules
  ansible.builtin.command: modprobe {{ item }}
  loop: "{{ kernel_modules }}"

- name: Create sysctl file for Kubernetes
  ansible.builtin.template:
    src: ../templates/sysctl_parameters.j2
    dest: /etc/sysctl.d/k8s.conf

- name: Apply sysctl settings for Kubernetes
  ansible.builtin.command: sysctl -p /etc/sysctl.d/k8s.conf

- name: Disable swap for the current session
  ansible.builtin.command: swapoff -a

- name: Add crontab entry to disable swap on boot
  ansible.builtin.cron:
    name: Disable swap on boot
    user: root
    job: /sbin/swapoff -a
    special_time: reboot
    state: present
    cron_file: swapoff